### PR TITLE
Fix `postMessage` when running on different env

### PR DESCRIPTION
**Pull request by blackxored**
Invocations of `postMessage` should differ when running on different environments,
and just the check for availability in `global` is not enough to avoid errors.
For example, when running on a WebWorker or (in my case) React Native, the second
argument needs to be of a different shape or omitted whatsoever. 

This PR checks for the presence of document as a reliable way of detecting where
we're running and modifies the invocation accordingly.

I've only tested the fix on the WebWorker scenario, but shouldn't have broken things on
browsers since the previous code is there and `document` it's available.

### CODE REVIEW

**Comment by michaelkantor** [comment]
My understanding is that this is just one of a number of React Native fixes that are needed, and that the body of work around those fixes is incomplete.  Correct me if I'm wrong; but based on that, I'm holding off on looking more closely at this.

**Comment by blackxored** [comment]
I don't think it's particular to React Native, I do agree that with RN's Chrome debugging might be the most common case, but I'd say any code that would run on a web worker would have this issue. I'm not completely up to date on to which frameworks are doing that under which conditions, but I know there was talk about it with at least Angular 2 and Aurelia moving code execution to web workers.

**Comment by michaelkantor** [comment]
It had been my intent to merge this into our next release; it had not been my expectation to have the kinds of delays and confusion involved in that next release.  I've created a new PR to get this added to the `WebSDK 3.0` release.

New PR is https://github.com/layerhq/layer-websdk/pull/131

**Comment by SpecialDOS** [comment]
@blackxored, I've been making some improvement to our RN support in websdk, and I came across this addition to our code for better RN support for postMessage. I'm curious how you have a postMessage method available in your react native environment? postMessage is not defined in my RN environment in the global scope. We want to make sure we are handling this appropriately for all RN environments, so any info you can give us would be helpful. Thanks!

**Comment by blackxored** [comment]
When running under Chrome (i.e Debug Remote JS) this is available. Might be
under other environments as well (react-native-debugger, IntelliJ's
debugger, etc).  Hope that helps.

—
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by SpecialDOS** [comment]
Thanks!

**Pull request closed without merging**
